
package com.example.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HotelServiceAvailabilityImplService", targetNamespace = "http://service.example.com/", wsdlLocation = "http://localhost:8080/ServerHotelSheraton/Availability?wsdl")
public class HotelServiceAvailabilityImplService
    extends Service
{

    private final static URL HOTELSERVICEAVAILABILITYIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException HOTELSERVICEAVAILABILITYIMPLSERVICE_EXCEPTION;
    private final static QName HOTELSERVICEAVAILABILITYIMPLSERVICE_QNAME = new QName("http://service.example.com/", "HotelServiceAvailabilityImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ServerHotelSheraton/Availability?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HOTELSERVICEAVAILABILITYIMPLSERVICE_WSDL_LOCATION = url;
        HOTELSERVICEAVAILABILITYIMPLSERVICE_EXCEPTION = e;
    }

    public HotelServiceAvailabilityImplService() {
        super(__getWsdlLocation(), HOTELSERVICEAVAILABILITYIMPLSERVICE_QNAME);
    }

    public HotelServiceAvailabilityImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HOTELSERVICEAVAILABILITYIMPLSERVICE_QNAME, features);
    }

    public HotelServiceAvailabilityImplService(URL wsdlLocation) {
        super(wsdlLocation, HOTELSERVICEAVAILABILITYIMPLSERVICE_QNAME);
    }

    public HotelServiceAvailabilityImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HOTELSERVICEAVAILABILITYIMPLSERVICE_QNAME, features);
    }

    public HotelServiceAvailabilityImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HotelServiceAvailabilityImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HotelServiceAvailability
     */
    @WebEndpoint(name = "HotelServiceAvailabilityImplPort")
    public HotelServiceAvailability getHotelServiceAvailabilityImplPort() {
        return super.getPort(new QName("http://service.example.com/", "HotelServiceAvailabilityImplPort"), HotelServiceAvailability.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HotelServiceAvailability
     */
    @WebEndpoint(name = "HotelServiceAvailabilityImplPort")
    public HotelServiceAvailability getHotelServiceAvailabilityImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.example.com/", "HotelServiceAvailabilityImplPort"), HotelServiceAvailability.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HOTELSERVICEAVAILABILITYIMPLSERVICE_EXCEPTION!= null) {
            throw HOTELSERVICEAVAILABILITYIMPLSERVICE_EXCEPTION;
        }
        return HOTELSERVICEAVAILABILITYIMPLSERVICE_WSDL_LOCATION;
    }

}
