
package com.example.client;

import com.example.exception.ReservationFailedException_Exception;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HotelServiceReservation", targetNamespace = "http://service.example.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HotelServiceReservation {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.example.client.Reservation
     * @throws ReservationFailedException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "makeReservation", targetNamespace = "http://service.example.com/", className = "com.example.client.MakeReservation")
    @ResponseWrapper(localName = "makeReservationResponse", targetNamespace = "http://service.example.com/", className = "com.example.client.MakeReservationResponse")
    @Action(input = "http://service.example.com/HotelServiceReservation/makeReservationRequest", output = "http://service.example.com/HotelServiceReservation/makeReservationResponse", fault = {
        @FaultAction(className = ReservationFailedException_Exception.class, value = "http://service.example.com/HotelServiceReservation/makeReservation/Fault/ReservationFailedException")
    })
    public Reservation makeReservation(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Object arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Object arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3)
        throws ReservationFailedException_Exception
    ;

}
